function nodeTable = Misc_InstalledRFeyeInfo(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NODETABLE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  NODETABLE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  nodeTable = importfile("C:\Users\Administrador\OneDrive - ANATEL\_MatlabProjects\Post-Processing\ReportGeneratorGUI\DataBase\QlikSense_RFeyePowerBI.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jan-2021 12:27:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Node", "Latitude", "Longitude", "Unit", "City"];
opts.VariableTypes = ["string", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Node", "Unit", "City"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Node", "Unit", "City"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Latitude", "Longitude"], "ThousandsSeparator", ",");

% Import the data
nodeTable = readtable(filename, opts);

end