function [htmlContent, emissionID] = htmlCode_EmissionInfo(specData, idx, idxEmission)

    emissionTag    = sprintf('%.3f MHz ⌂ %.1f kHz', specData(idx).UserData.Emissions.Frequency(idxEmission), specData(idx).UserData.Emissions.BW(idxEmission));

    bandFreqStart  = sprintf('%.3f MHz', specData(idx).MetaData.FreqStart/1e+6);
    bandFreqStop   = sprintf('%.3f MHz', specData(idx).MetaData.FreqStop/1e+6);
    bandStepWidth  = sprintf('%.1f kHz', (specData(idx).MetaData.FreqStop - specData(idx).MetaData.FreqStart)/(1000*(specData(idx).MetaData.DataPoints-1)));
    bandResolution = sprintf('%.1f kHz', specData(idx).MetaData.Resolution/1000);

    metaData       = struct('FreqStart',        bandFreqStart,                           ...
                            'FreqStop',         bandFreqStop,                            ...
                            'DataPoints',       specData(idx).MetaData.DataPoints,       ...
                            'StepWidth',        bandStepWidth,                           ...
                            'Resolution',       bandResolution,                          ...
                            'TraceMode',        specData(idx).MetaData.TraceMode,        ...
                            'TraceIntegration', specData(idx).MetaData.TraceIntegration, ...
                            'Detector',         specData(idx).MetaData.Detector,         ...
                            'LevelUnit',        specData(idx).MetaData.LevelUnit);

    dataStruct(1)  = struct('group', 'RECEPTOR',            'value', specData(idx).Receiver);
    dataStruct(2)  = struct('group', 'TEMPO DE OBSERVAÇÃO', 'value', sprintf('%s - %s', datestr(specData(idx).Data{1}(1),   'dd/mm/yyyy HH:MM:SS'), datestr(specData(idx).Data{1}(end), 'dd/mm/yyyy HH:MM:SS')));
    dataStruct(3)  = struct('group', 'METADADOS',           'value', metaData);

    htmlContent    = [sprintf('<p style="font-family: Helvetica, Arial, sans-serif; font-size: 16px; text-align: justify; line-height: 12px; margin: 5px; padding-top: 5px; padding-bottom: 10px;"><b>%s</b></p>', emissionTag) ...
                      textFormatGUI.struct2PrettyPrintList(dataStruct, 'delete')];

    emissionID     = struct('Thread',   struct('Index',     idx,                                                     ...
                                               'UUID',      {specData(idx).RelatedFiles.uuid}),                      ...
                            'Emission', struct('Index',     idxEmission,                                             ...
                                               'Frequency', specData(idx).UserData.Emissions.Frequency(idxEmission), ...
                                               'BW',        specData(idx).UserData.Emissions.BW(idxEmission),        ...
                                               'Tag',       emissionTag));
end