function xArray = XArray(app, idx)
    xArray = linspace(app.specData(idx).MetaData.FreqStart / 1e+6, ...
                      app.specData(idx).MetaData.FreqStop  / 1e+6, ...
                      app.specData(idx).MetaData.DataPoints);
end