classdef UserData

    properties
        %-----------------------------------------------------------------%
        customPlayback        = struct('Type', 'auto', 'Parameters', [])

        occCache              = struct('Info', {}, 'THR', {}, 'Data', {})
        occMethod             = struct('RelatedIndex', [], 'SelectedIndex', [], 'CacheIndex', [])

        channelLibIndex       = []
        channelManual         = struct('Name', {}, 'Band', {}, 'FirstChannel', {}, 'LastChannel', {}, 'StepWidth', {}, 'ChannelBW', {}, 'FreqList', {}, 'Reference', {}, 'FindPeaksName', {})

        bandLimitsStatus      = false
        bandLimitsTable       = table('Size', [0, 2],                        ...
                                      'VariableTypes', {'double', 'double'}, ...
                                      'VariableNames', {'FreqStart', 'FreqStop'})

        Emissions             = table(uint32([]), [], [], true(0,1), string.empty,                                                                                                                                      ...
                                      struct('Detection', {}, 'Classification', {}, 'Occupancy', {}, 'BandWidth', {}),                                                                                                  ...
                                      struct('Level', {}, 'FCO', {}, 'FBO', {}, 'BandWidth', {}),                                                                                                                       ...
                                      struct('Regulatory', {}, 'Service', {}, 'Station', {}, 'Latitude', {}, 'Longitude', {}, 'Description', {}, 'Distance', {}, 'EmissionType', {}, 'Irregular', {}, 'RiskLevel', {}), ...
                                      struct('Regulatory', {}, 'Service', {}, 'Station', {}, 'Latitude', {}, 'Longitude', {}, 'Description', {}, 'Distance', {}, 'EmissionType', {}, 'Irregular', {}, 'RiskLevel', {}), ...
                                      struct('SignalAnalysis', {}, 'DriveTest', {}),                                                                                                                                    ...
                                      'VariableNames', {'idxFrequency', 'Frequency', 'BW_kHz', 'isTruncated', 'Description', 'Algorithm', 'Measures', 'suggestedClassification', 'pointedClassification', 'auxAppData'})

        measCalibration       = table('Size', [0, 4],                                    ...
                                      'VariableTypes', {'cell', 'cell', 'cell', 'cell'}, ...
                                      'VariableNames', {'Name', 'Type', 'oldUnitLevel', 'newUnitLevel'})

        reportFlag            = false
        reportOCC             = []
        reportDetection       = [] % struct('ManualMode', 0, 'Algorithm', {}, 'Parameters', {})
        reportClassification  = [] % struct('Algorithm', {}, 'Parameters', {})
        reportPeaksTable      = []
        reportExternalFiles   = table('Size', [0, 4],                                    ...
                                      'VariableTypes', {'cell', 'cell', 'cell', 'int8'}, ...
                                      'VariableNames', {'Type', 'Tag', 'Filename', 'ID'});
        reportChannelTable    = []
        reportChannelAnalysis = []

        AntennaHeight         = []

        % Registrar operações não contempladas nas outras propriedades. Por
        % exemplo: filtragem temporal do fluxo espectral.
        LOG                   = {}
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function fieldTemplate = getFieldTemplate(dataType)
            arguments
                dataType {mustBeMember(dataType, {'Measures:Level',              ...
                                                  'Measures:BandWidth',          ...
                                                  'Measures:FCO',                ...
                                                  'Measures:FBO',                ...
                                                  'auxAppData:SignalAnalysis',   ...
                                                  'DefaultAlgorithm: Occupancy', ...
                                                  'DefaultAlgorithm: Detection', ...
                                                  'DefaultAlgorithm: Classification'})}
            end

            switch dataType
                case 'Measures:Level'
                    fieldTemplate = struct('FreqCenter_Min',      {},  ...
                                           'FreqCenter_Mean',     {},  ...
                                           'FreqCenter_Max',      {},  ...
                                           'Channel_Min',         {},  ...
                                           'Channel_Mean',        {},  ...
                                           'Channel_Max',         {});

                case 'Measures:BandWidth'
                    fieldTemplate = struct('Min',                 {},  ...
                                           'Mean',                {},  ...
                                           'Max',                 {});

                case 'Measures:FCO'
                    fieldTemplate = struct('FreqCenter_Infinite', {},  ...
                                           'Channel_Infinite',    {},  ...
                                           'Channel_Finite_Min',  {},  ...
                                           'Channel_Finite_Mean', {},  ...
                                           'Channel_Finite_Max',  {});

                case 'Measures:FBO'
                    fieldTemplate = struct('Channel_Min',         {},  ...
                                           'Channel_Mean',        {},  ...
                                           'Channel_Max',         {});

                case 'auxAppData:SignalAnalysis'
                    fieldTemplate = struct('ChannelAssigned', struct('Frequency', {}, 'ChannelBW', {}));

                case 'DefaultAlgorithm: Occupancy'
                    fieldTemplate = struct('Method',              'Linear adaptativo', ...
                                           'IntegrationTime',     15,                  ...
                                           'Offset',              12,                  ...
                                           'noiseFcn',            'mean',              ...
                                           'noiseTrashSamples',   0.10,                ...
                                           'noiseUsefulSamples',  0.20);

                case 'DefaultAlgorithm: Detection'
                    fieldTemplate = struct('ManualMode', 0,                         ...
                                           'Algorithm', 'FindPeaks+OCC',            ...
                                           'Parameters', struct('Distance_kHz', 25, ... % kHz
                                                                'BW_kHz',       10, ... % kHz
                                                                'Prominence1',  10, ...
                                                                'Prominence2',  30, ...
                                                                'meanOCC',      10, ...
                                                                'maxOCC',       67));

                case 'DefaultAlgorithm: Classification'
                    fieldTemplate = struct('Algorithm',  'Frequency+Distance Type 1', ...
                                           'Parameters', struct('Contour', 30,        ...
                                                                'ClassMultiplier', 2, ...
                                                                'bwFactors', [100, 300]));

                case 'DefaultClassification'
                    fieldTemplate = struct('Regulatory',   'Não licenciada',         ...
                                           'Service',      int16(-1),                ...
                                           'Station',      int32(-1),                ...
                                           'Latitude',     -1,                       ...
                                           'Longitude',    -1,                       ...
                                           'Description',  '-',                      ...
                                           'Distance',     -1,                       ...
                                           'EmissionType', 'Pendente identificação', ...
                                           'Irregular',    'Sim',                    ...
                                           'RiskLevel',    'Baixo');
            end
        end
    end
end