function romesTable = RomesCSV(fileName)
    %  ROMESCSV Auto-generated by MATLAB on 08-Jan-2024 15:31:06
    
    opts = delimitedTextImportOptions("NumVariables", 12);
    
    % Specify range and delimiter
    opts.DataLines = [3, Inf];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["Sweep", "MinFreqMHz", "MaxFreqMHz", "Technology", "Band", "Frequency", "Channel", "BW", "MCC", "Notes", "Provider", "Comment"];
    opts.SelectedVariableNames = ["Technology", "Band", "Frequency", "Channel", "BW", "Notes"];
    opts.VariableTypes = ["categorical", "double", "double", "categorical", "double", "double", "string", "double", "double", "string", "categorical", "categorical"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, ["Sweep", "Technology", "Channel", "Notes", "Provider", "Comment"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, ["MinFreqMHz", "MaxFreqMHz", "Band", "Frequency", "BW"], "FillValue", 0);
    
    % Import the data
    romesTable      = readtable(fileName, opts);
    
    romesTable.BW   = 1000 * romesTable.BW;
    romesTable.Info = string(romesTable.Technology) + ", " + string(romesTable.Band) + ", " + romesTable.Channel + ", " + romesTable.Notes;

    romesTable      = romesTable(:,[3,5,7]);
end